name: Bump version

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]

jobs:
  check-label:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: Retrieve version label
        run: |
          VERSION_LABEL=$(gh pr view $PR_NUMBER --json labels --jq '.labels | map(select(.name == "v:major" or .name == "v:minor" or .name == "v:patch")) | sort_by(.name) | .[0].name')
          echo "Version label detected: $VERSION_LABEL"
          echo "version_label=$VERSION_LABEL" >> $GITHUB_OUTPUT
