name: Some checks

on:
  pull_request:
  workflow_run:
    types: completed
    workflows: [Synchronise Version]

jobs:
  check-things:
    runs-on: ubuntu-latest
    steps:
      - name: is true
        run: |
          echo "hello world" || true
